create table library_branch (
    id bigint generated by default as identity primary key,
    code varchar(30) not null unique,
    name varchar(120) not null,
    address varchar(255),
    phone varchar(50),
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

insert into library_branch (id, code, name, address, phone, active, created_at, updated_at)
values
    (1, 'CENTRAL', 'Central Knowledge Library', '1 Archive Square, District 1', '+84-28-7300-1001', true, current_timestamp, current_timestamp),
    (2, 'EAST', 'East Research Library', '88 Innovation Avenue, Thu Duc', '+84-28-7300-1002', true, current_timestamp, current_timestamp),
    (999, 'HQ', 'Library Headquarters', '99 Operations Plaza, District 7', '+84-28-7300-1999', true, current_timestamp, current_timestamp);

alter table app_user
    add constraint fk_app_user_branch
        foreign key (branch_id) references library_branch(id);

alter table app_user
    add constraint fk_app_user_home_branch
        foreign key (home_branch_id) references library_branch(id);

select setval('library_branch_id_seq', (select max(id) from library_branch));
